import { AvatarOptions } from "@avatar-core/src";

export const AVATAR_OPTIONS: AvatarOptions[] = [
    {
        name: "John Doe",
        backgroundColor: "#4CAF50",
        shape: "circle",
        textColor: "#000",
        fontSize: "30px",
        width: "120px",
        height: "120px",
        tooltip: true,
        additionalClasses: "avatar-shadow",
    },
    {
        name: "Jane Smith",
        backgroundColor: ["#2196F3", "#21CBF3"],
        textColor: "#fff",
        fontSize: "40px",
        width: "100px",
        height: "100px",
        tooltip: true,
        additionalClasses: "avatar-gradient",
    },
    {
        name: "Josh Stanley",
        backgroundColor: ["#2196F3", "#21CBF3"],
        gradientDirection: "horizontal",
        textColor: "#fff",
        fontSize: "40px",
        width: "100px",
        height: "100px",
        tooltip: true,
        additionalClasses: "avatar-gradient",
    },
    {
        name: "Chris Evans",
        backgroundColor: "#FF5722",
        shape: "circle",
        width: "150px",
        height: "150px",
        tooltip: true,
        additionalClasses: "avatar-image",
    },
    {
        name: "Peter",
        backgroundColor: "#F52322",
        fontSize: "50px",
        shape: "square",
        tooltip: false,
    },
];
